### ISSUE TITLE
Structure of Saved Policy Note

### ISSUE THREAD

**Issue by mgravitt** [coinstr/coinstr#37]
Some data within a coinstr policy is required as part of the policy itself, namely the output descriptor. 

There is other metadata that may need to be stored with the policy that is used by the UI. For example, the blockly interface requires the `xml` field shown in the below.

Also, in the below, the keys represent users that are "Added to Policy" but may or may not be actually part of the output descriptor. In these cases, I think only the keys themselves are likely enough data since the contact list metadata will be retrieved by the UI every time the user logs in anyways. 

```json
{
    "xml": "<xml xmlns=\"https://developers.google.com/blockly/xml\"><block type=\"begin\" id=\"s3zMsKO[BDKY-|`ZE|Go\" deletable=\"false\" editable=\"false\" x=\"260\" y=\"10\"><field name=\"SPACE\"> </field><next><block type=\"thresh\" id=\"mgx]p@,N7_vgutsXjI?G\"><field name=\"Threshold\">1</field><field name=\"SPACE\"> </field><statement name=\"Statements\"><block type=\"pk\" id=\"E$tv{1KVJze^2#u{#tI+\"><value name=\"Key\"><block type=\"my_key\" id=\"F?Up(j{OmcNe^o^.;ffT\"/></value><next><block type=\"pk\" id=\"Y]F2x(BiZ|Y.m}bc29P@\"><value name=\"Key\"><block type=\"key\" id=\"=Vizxf0dm0nQQ:PNxG(I\"><field name=\"Key\">101e7953a54b18d0f41ea199b9adf2d7e643441b5af8e539531e6d7275cee1df</field></block></value></block></next></block></statement></block></next></block></xml>",
    "policyCode": "thresh(1,pk(ea527e059759d368a55253270454e58e9d6e4fe2e98d302d6e01821fa973259d),pk(101e7953a54b18d0f41ea199b9adf2d7e643441b5af8e539531e6d7275cee1df))",
    "keys": [
        [
            {
                "about": "Vice Chairperson, Water Well",
                "banner": "https://coinstr.app/coinstr.png",
                "display_name": "John Chen",
                "name": "john",
                "nip05": "john@waterwell.ngo",
                "picture": "https://img.freepik.com/premium-vector/profile-icon-male-avatar-hipster-man-wear-headphones_48369-8728.jpg",
                "npub": "npub1zq08j5a9fvvdpaq75xvmnt0j6lnyx3qmttuw2w2nrekhyawwu80s7tz8rm",
                "bitcoinAddress": "101e7953a54b18d0f41ea199b9adf2d7e643441b5af8e539531e6d7275cee1df",
                "isSelectable": true,
                "label": "John Chen",
                "pk": "101e7953a54b18d0f41ea199b9adf2d7e643441b5af8e539531e6d7275cee1df"
            }
        ]
    ]
}
```

**Comment by mgravitt** [comment]
@yukibtc what is the structure of the policy that is saved as a note currently? Is it only the output descriptor? 

Does it make sense to add something like `ui_metadata` which could store the above `xml` and key list? Then, if a client knows how to render it, like the Blockly client with the xml, or else it could ignore it.

**Comment by mgravitt** [comment]
Maybe something like this: 
```json
{
   "output_descriptor": "",
   "ui_metadata": {
          "xml": "<xml ...> </xml>",
          "keys": [key1, key2, key3, key4...]
   }
}
```

**Comment by yukibtc** [comment]
The nostr public keys are already saved in the tags of the policy event (I can write a function to extract from tags easily).
Regarding the XML data, I don't know if is a good idea.
In general, is better to use JSON instead of XML ([check here](https://developers.google.com/blockly/guides/configure/web/serialization#choosing_between_json_and_xml).

I think that is better to generate the blockly struct directly from the descriptor, like you have done in `get policy` command with `termtree`), so if I import the descriptor from, for example, a backup, the UI will be shown (this will not happen using the above solution).

I'll try to write a function to compose the blockly JSON from a descriptor. 

https://developers.google.com/blockly/guides/get-started/web#importing_and_exporting_blocks

**Comment by mgravitt** [comment]
The one requirement that wouldn't be covered is that accounts can be added to the blockly area but not in the actual policy. 

They show up in drop downs for keys but the miniscript may not contain that key. It's like for draft policies. 

We also need to disable edits after the policy has received BTC, since it is needed to spend on that BTC and could be lost if edits are allowed.
