### ISSUE TITLE
Fix Compilation Error with "make gui" Command on MacBook Pro M2

### ISSUE THREAD

**Issue by jmgayosso** [coinstr/coinstr#68]
### Description
When executing the "make gui" command on a MacBook Pro M2, the following error is encountered: " note: ld: warning: ignoring file /Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64  Undefined symbols for architecture arm64:". This error indicates a syntax issue with specifying the architectures.

### Task Description
Investigate and resolve the compilation error that occurs when running the "make gui" command on a MacBook Pro M2.

![Image](https://github.com/coinstr/coinstr/assets/58195358/f090e0e4-ea0b-42f6-a61f-00f8a62d1d7e)

![Image](https://github.com/coinstr/coinstr/assets/58195358/f2b512ed-6ab9-487a-a955-1b8a81493ce1)

**Reason for Changes**
Fixing the compilation error is crucial to ensure a successful build of the project. By addressing the syntax issue and providing possible solutions, the "make gui" command can be executed without errors on the MacBook Pro M2. Resolving this issue allows for further development and testing of the project.

**Comment by yukibtc** [comment]
The HWI library require python to compile the release.
I'll replace that library with another one written in pure rust.

For now, to fix the issue, you can try to compile it in debug mode with `cargo build -p coinstr` or to install python: https://www.python.org/downloads/

**Comment by yukibtc** [comment]
Can you try if now works?

I added a feature to enable/disable the `hwi` library (by default is disabled).
